server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    com.netflix.discovery: TRACE
    #reactor.netty.http.client: DEBUG
    root: INFO

############ Eureka Configs ############
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

########### Actuator Configs #########


########## API Gateway Configs ########
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: route1
          uri: https://httpbin.org
          predicates:
            - Path=/uuid